name: "Phaser Export"

on:
  push:
    branches:
      - "Phaser-3-Arcade-Version"
  pull_request:
    branches:
      - "Phaser-3-Arcade-Version"

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install and build
        run: npm install && npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: dist
#      - name: Deploy to GitHub Pages ðŸš€
#        uses: JamesIves/github-pages-deploy-action@releases/v4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: dist # The folder the action should deploy.
